name: timer

run-name: Timer

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Get start time
        run: echo "START_TIME=$(date +%s)" >> $GITHUB_ENV
  do-something:
    runs-on: ubuntu-latest
    steps:
      - name: Do something
        run: sleep 60 * 2
  end:
    runs-on: ubuntu-latest
    steps:
      - name: Get end time
        run: echo "END_TIME=$(date +%s)" >> $GITHUB_ENV
      - name: Get run time minutes
        run: echo "RUN_TIME_MINUTES=$((($END_TIME - $START_TIME)/60))" >> $GITHUB_ENV
      - name: Fail if run time is 10 minutes or more
        if: $RUN_TIME_MINUTES >= 10
        run: exit 1
