name: timer

run-name: Timer

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Get start time
        run: START_TIME=$(date +%s)
  do-something:
    runs-on: ubuntu-latest
    steps:
      - name: Do something
        run: sleep 60 * 2
  end:
    runs-on: ubuntu-latest
    steps:
      - name: Get end time
        run: END_TIME=$(date +%s)
      - name: Get run time minutes
        run: RUN_TIME_MINUTES=$((($END_TIME - $START_TIME)/60))
      - name: Fail if run time is 10 minutes or more
        if: RUN_TIME_MINUTES >= 10
        run: exit 1
